# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# MQTT Configuration
mqtt:
  # MQTT Sensors
  sensor:
    - name: "Temperature"
      unique_id: temperature_mqtt
      state_topic: "homeassistant/sensor"
      device_class: temperature
      value_template: "{{ value_json.temp }}"
      unit_of_measurement: "°C"

    - name: "Humidity"
      unique_id: humidity_mqtt
      state_topic: "homeassistant/sensor"
      device_class: humidity
      value_template: "{{ value_json.humid }}"
      unit_of_measurement: "%"

    - name: "Light"
      unique_id: light_mqtt
      state_topic: "homeassistant/sensor"
      device_class: illuminance
      value_template: "{{ value_json.lux }}"
      unit_of_measurement: "lx"
    - name: "TEST E"
      unique_id: enerytest
      state_topic: "homeassistant/speedtest"
      device_class: energy
      value_template: "{{ value_json.val }}"
      unit_of_measurement: "J"

  # MQTT Binary Sensor
  binary_sensor:
    - name: "LED State"
      state_topic: "homeassistant/led/state"
      payload_on: "on"
      payload_off: "off"
      device_class: light
    - name: "Motion"
      unique_id: motion_mqtt
      state_topic: "homeassistant/sensor"
      value_template: "{{ value_json.motion }}"
      payload_on: "on"
      payload_off: "off"
      device_class: motion
# Shell Command
shell_command:
  update_bearer_token: python3 /config/get_update_token.py

